name: Node.js CI

on:
  push:
    branches:
      - main
    paths:
      - 'backend/**'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Setup Node.js environment
        uses: actions/setup-node@v2
        with:
          node-version: '14'

      - name: Install dependencies
        run: yarn  install
        working-directory: 'backend'

      - name: Create dist directory
        run: mkdir backend/dist

      - name: Build project
        run: yarn  build  
        working-directory: 'backend'

      - name: Run tests
        run: yarn  test  
        working-directory: 'backend'

      - name: Deploy application
        run: |
          echo "Deploying the application..."
