name: Node.js CI

on:
  push:
    branches: 'main'
    paths: [backend/**]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '14.x'  # 원하는 Node.js 버전으로 변경하세요

      - name: Clear npm cache
        run: npm cache clean --force

      - name: Update npm dependencies
        run: npm install --legacy-peer-deps

      - name: Install dependencies
        run: npm ci

      - name: Build project
        run: npm run build --if-present

      - name: Run linting
        run: npm run lint

      - name: Run tests
        run: npm test
